name: Build and Release

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure CI Git User
        run: |
          git config --global user.name 'DecliningLotus'
          git config --global user.email 'DecliningLotus@users.noreply.github.com'
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_PAT@github.com/DecliningLotus/fontsource-playground
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

      - name: Install packages
        run: yarn

      - name: Build fonts
        run: yarn build-google

      - name: Stage changes
        run: git add .

      - name: Commit files
        run: >-
          git commit -m "chore(build): update fontsources $GITHUB_RUN_NUMBER"
        continue-on-error: true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish package
        run: npm run deploy:ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
